# Generated by Django 4.2 on 2023-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0003_restaturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaturant',
            name='Ownername',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='restaturant',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='null', max_length=100),
        ),
    ]
