# Generated by Django 4.2 on 2023-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0005_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='ItemId',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
