# Generated by Django 4.2 on 2023-05-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0006_alter_fooditems_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='RestaturantId',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EpicureApp.restaturant'),
        ),
    ]
