# Generated by Django 4.2 on 2023-05-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0008_delete_fooditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('ItemId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Starters', 'Starters'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100)),
                ('Image', models.FileField(upload_to='FoodImages/')),
                ('RestaturantId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EpicureApp.restaturant')),
            ],
        ),
    ]
