# Generated by Django 4.2 on 2023-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0009_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='RestaturantId',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
