# Generated by Django 4.2 on 2023-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0011_alter_fooditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('email', models.EmailField(max_length=100)),
                ('OrderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ItemsInfo', models.CharField(max_length=1000)),
                ('TotalCost', models.CharField(max_length=1000)),
                ('Address', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('Phone', models.CharField(max_length=1000)),
                ('PaymentStatus', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=1000)),
                ('Date', models.CharField(max_length=1000)),
                ('Time', models.CharField(max_length=1000)),
                ('OrderType', models.CharField(max_length=1000)),
            ],
        ),
    ]
