# Generated by Django 4.2 on 2023-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0012_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderType',
            field=models.CharField(choices=[('Home Delivery', 'Home Delivery'), ('Pickup', 'Pickup'), ('Dine In', 'Dine In')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='PaymentStatus',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cooking', 'Cooking'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=1000),
        ),
    ]
