# Generated by Django 4.2 on 2023-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0013_alter_orders_ordertype_alter_orders_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Time',
            field=models.TimeField(max_length=1000),
        ),
    ]
