# Generated by Django 4.2 on 2023-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0014_alter_orders_date_alter_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cooking', 'Cooking'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=1000),
        ),
    ]
