# Generated by Django 4.2 on 2023-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0015_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaturant',
            name='Image',
            field=models.FileField(default='null', upload_to='RestaurantImages/'),
        ),
    ]
