# Generated by Django 4.2 on 2023-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicureApp', '0017_itemwiseorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwiseorders',
            name='RestaturantId',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
